### PR TITLE
Change first point in trajectory to commanded position

### PR DESCRIPTION
**Pull request by pazeshun**
Same as https://github.com/RethinkRobotics/baxter_interface/pull/77

### CODE REVIEW

**Comment by pazeshun** [comment]
Ping @wkentaro

**Comment by pazeshun** [comment]
Ping @wkentaro

**Comment by wkentaro** [comment]
Is this tested with real robot?

**Comment by pazeshun** [comment]
Yes. With master branch of jsk_apc.

**Comment by k-okada** [comment]
With this PRj, gazebo simulation is not working, joint_trajectory_action do not generate command because of errors,

```
$ rosrun baxter_interface joint_trajectory_action_server.py --interpolation minjerk
[ERROR] [WallTime: 1501462702.406211] [2142.279000] /rsdk_position_w_id_joint_trajectory_action_server: Exceeded Error Threshold on left_s1: 0.999433532707
[ERROR] [WallTime: 1501462702.407546] [2142.279000] /rsdk_position_w_id_joint_trajectory_action_server: Exceeded Error Threshold on right_s0: 0.653352615824
```

If we revert following lines, we can solve the problem.
```
-            first_trajectory_point.positions = self._get_current_position(joint_names)
+            first_trajectory_point.positions = self._get_commanded_position(joint_names)
```
Why you have to use `comanded_position` the first trajectory point??? @pazeshun

**Comment by pazeshun** [comment]
`current_position` comes from `/robot/joint_states` which may be different from the `commanded_position`.
Please see https://github.com/jsk-ros-pkg/jsk_robot/issues/738#issue-193413329 and https://github.com/RethinkRobotics/baxter_interface/pull/77#issue-193695002 for detailed information.

**Comment by pazeshun** [comment]
I've also heard simulator problem like https://github.com/start-jsk/jsk_apc/issues/2106#issuecomment-304183748.
Perhaps we have to stop using `commanded_position`...

**Comment by k-okada** [comment]
thank you for information, Yes I just fixed this problem by writing as same code as https://github.com/start-jsk/jsk_apc/issues/2106#issuecomment-304184560 ...

**Comment by k-okada** [comment]
A robot in gazebo shaking, but the data is clean, need to check on real robot

screenshot from 2017-07-31 17 07 51


```
rqt_plot -b pyqt /robot/limb/left/joint_command/command[0],/robot/limb/left/joint_command/command[1],/robot/limb/left/joint_command/command[2],/robot/limb/left/joint_command/command[3],/robot/limb/left/joint_command/command[4],/robot/limb/left/joint_command/command[5],/robot/limb/left/joint_command/command[6]  /robot/limb/left/follow_joint_trajectory/goal/goal/trajectory/points[0]/positions[0]  /robot/limb/left/follow_joint_trajectory/goal/goal/trajectory/points[0]/positions[1]  /robot/limb/left/follow_joint_trajectory/goal/goal/trajectory/points[0]/positions[2]  /robot/limb/left/follow_joint_trajectory/goal/goal/trajectory/points[0]/positions[3]  /robot/limb/left/follow_joint_trajectory/goal/goal/trajectory/points[0]/positions[4]  /robot/limb/left/follow_joint_trajectory/goal/goal/trajectory/points[0]/positions[5]  /robot/limb/left/follow_joint_trajectory/goal/goal/trajectory/points[0]/positions[6]
```

**Pull request merged**
